### ISSUE TITLE
ES6 webpack5 and babel warning (and js errors)

### ISSUE THREAD

**Issue by florent-cdl** [smart-table/smart-table-react#7]
Hi,

I've got alot of warning which results in js error on the browser : 
_WARNING in ./node_modules/smart-table-react/lib/filters.js 3:20-26
export 'filter' (imported as 'filter') was not found in 'smart-table-core' (possible exports: FilterOperator, FilterType, SmartTableEvents, SortDirection, filterDirective, paginationDirective, searchDirective, sliceFactory, smartTable, sortDirective, summaryDirective, tableDirective, workingIndicatorDirective)_
For each import like this one I've got an alert. Perhaps there is possible modifications that can be done on the project to avoird such a problems ?
Thank you
Best regards.
Florent

**Comment by lorenzofox3** [comment]
Hi. 

The react/preact adapter is not really maintained anymore. However you can see how to use smart-table with react in [this repository](https://github.com/lorenzofox3/lls-test/tree/master/app).

Instructions are in French though
